//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTUITOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_lessons
    {
        public int hl_id { get; set; }
        public Nullable<int> tutor_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public string subject { get; set; }
        public string @class { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public Nullable<int> total_sessions { get; set; }
        public string day_otw { get; set; }
        public Nullable<System.DateTime> day { get; set; }
    
        public virtual student student { get; set; }
        public virtual tutor tutor { get; set; }
    }
}
