//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTUITOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int us_id { get; set; }
        public string us_usname { get; set; }
        public string us_pw { get; set; }
        public int us_type { get; set; }
    
        public virtual typeUser typeUser { get; set; }
    }
}
